//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/UIActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

namespace GameUI
{
    public partial class @UIControls: IInputActionCollection2, IDisposable
    {
        public InputActionAsset asset { get; }
        public @UIControls()
        {
            asset = InputActionAsset.FromJson(@"{
    ""name"": ""UIActions"",
    ""maps"": [
        {
            ""name"": ""UIControlls"",
            ""id"": ""192980de-cac0-4c16-85c4-bc10f0ea30de"",
            ""actions"": [
                {
                    ""name"": ""Esc"",
                    ""type"": ""Button"",
                    ""id"": ""fc2efc92-32d0-41ef-95cd-936f01cdccb6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""381d88e6-261b-4057-9772-d3a69768a97c"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Esc"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
            // UIControlls
            m_UIControlls = asset.FindActionMap("UIControlls", throwIfNotFound: true);
            m_UIControlls_Esc = m_UIControlls.FindAction("Esc", throwIfNotFound: true);
        }

        public void Dispose()
        {
            UnityEngine.Object.Destroy(asset);
        }

        public InputBinding? bindingMask
        {
            get => asset.bindingMask;
            set => asset.bindingMask = value;
        }

        public ReadOnlyArray<InputDevice>? devices
        {
            get => asset.devices;
            set => asset.devices = value;
        }

        public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

        public bool Contains(InputAction action)
        {
            return asset.Contains(action);
        }

        public IEnumerator<InputAction> GetEnumerator()
        {
            return asset.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }

        public void Enable()
        {
            asset.Enable();
        }

        public void Disable()
        {
            asset.Disable();
        }

        public IEnumerable<InputBinding> bindings => asset.bindings;

        public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
        {
            return asset.FindAction(actionNameOrId, throwIfNotFound);
        }

        public int FindBinding(InputBinding bindingMask, out InputAction action)
        {
            return asset.FindBinding(bindingMask, out action);
        }

        // UIControlls
        private readonly InputActionMap m_UIControlls;
        private List<IUIControllsActions> m_UIControllsActionsCallbackInterfaces = new List<IUIControllsActions>();
        private readonly InputAction m_UIControlls_Esc;
        public struct UIControllsActions
        {
            private @UIControls m_Wrapper;
            public UIControllsActions(@UIControls wrapper) { m_Wrapper = wrapper; }
            public InputAction @Esc => m_Wrapper.m_UIControlls_Esc;
            public InputActionMap Get() { return m_Wrapper.m_UIControlls; }
            public void Enable() { Get().Enable(); }
            public void Disable() { Get().Disable(); }
            public bool enabled => Get().enabled;
            public static implicit operator InputActionMap(UIControllsActions set) { return set.Get(); }
            public void AddCallbacks(IUIControllsActions instance)
            {
                if (instance == null || m_Wrapper.m_UIControllsActionsCallbackInterfaces.Contains(instance)) return;
                m_Wrapper.m_UIControllsActionsCallbackInterfaces.Add(instance);
                @Esc.started += instance.OnEsc;
                @Esc.performed += instance.OnEsc;
                @Esc.canceled += instance.OnEsc;
            }

            private void UnregisterCallbacks(IUIControllsActions instance)
            {
                @Esc.started -= instance.OnEsc;
                @Esc.performed -= instance.OnEsc;
                @Esc.canceled -= instance.OnEsc;
            }

            public void RemoveCallbacks(IUIControllsActions instance)
            {
                if (m_Wrapper.m_UIControllsActionsCallbackInterfaces.Remove(instance))
                    UnregisterCallbacks(instance);
            }

            public void SetCallbacks(IUIControllsActions instance)
            {
                foreach (var item in m_Wrapper.m_UIControllsActionsCallbackInterfaces)
                    UnregisterCallbacks(item);
                m_Wrapper.m_UIControllsActionsCallbackInterfaces.Clear();
                AddCallbacks(instance);
            }
        }
        public UIControllsActions @UIControlls => new UIControllsActions(this);
        public interface IUIControllsActions
        {
            void OnEsc(InputAction.CallbackContext context);
        }
    }
}
